### ISSUE TITLE
Deadlock in bump function

### ISSUE THREAD

**Issue by imlonghao** [leahneukirchen/lywsd03mmc-exporter#2]
https://github.com/leahneukirchen/lywsd03mmc-exporter/blob/d57c5b255f591dc486fa36447d3999084ccff011/lywsd03mmc-exporter.go#L116-L136

The line 117 acquire the expirersLock, then the line 130 acquire the same lock again, which cause the program in deadlock

**Comment by imlonghao** [comment]
Sorry, it seems I make some misunderstanding about this code.

**Comment by leahneukirchen** [comment]
The inner lock runs from a timer.AfterFunc, which is in a different goroutine (and delayed).  So I don't think this can deadlock.
